{{- if and .Values.gitMirrorStorage.enabled (not .Values.gitMirrorStorage.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gecko.fullname" . }}-git-mirror
  labels:
    {{- include "gecko.labels" . | nindent 4 }}
    {{- with .Values.gitMirrorStorage.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gitMirrorStorage.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.gitMirrorStorage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.gitMirrorStorage.size | quote }}
  {{- with .Values.gitMirrorStorage.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
