{{- if and .Values.qdrant.enabled .Values.qdrant.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-storage-pv
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: "default"
spec:
  capacity:
    storage: {{ .Values.qdrant.persistence.size | quote }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.qdrant.persistence.storageClass | quote }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.qdrant.persistence.hostPath | quote }}
{{- end }}
