# Shared upstream
set $drs_upstream http://drs-server$des_domain:8080;

# GA4GH DRS
location ^~ /ga4gh/ {
    if ($csrf_check !~ ^ok-\S.+$) {
     return 403 "failed csrf check";
    }

    set $proxy_service "drs-server";
    proxy_pass $drs_upstream;
    proxy_redirect http://$host/ https://$host/;
}

# Index API (exact + subtree)
location /index {
    set $proxy_service "drs-server";
    proxy_pass $drs_upstream;
    proxy_redirect http://$host/ https://$host/;
}

location ^~ /index/ {
    if ($csrf_check !~ ^ok-\S.+$) {
     return 403 "failed csrf check";
    }

    set $proxy_service "drs-server";
    proxy_pass $drs_upstream;
    proxy_redirect http://$host/ https://$host/;
}

# Upload / download canonical routes
location ^~ /upload {

    set $proxy_service "drs-server";
    proxy_pass $drs_upstream;
    proxy_redirect http://$host/ https://$host/;

    # multipart helpers
    client_max_body_size 0;
    proxy_request_buffering off;
    proxy_buffering off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
}

location ^~ /download/ {
    if ($csrf_check !~ ^ok-\S.+$) {
     return 403 "failed csrf check";
    }

    set $proxy_service "drs-server";
    proxy_pass $drs_upstream;
    proxy_redirect http://$host/ https://$host/;
}

# Git LFS transport
location ^~ /info/lfs/ {
    if ($csrf_check !~ ^ok-\S.+$) {
     return 403 "failed csrf check";
    }

    set $proxy_service "drs-server";
    proxy_pass $drs_upstream;
    proxy_redirect http://$host/ https://$host/;

    client_max_body_size 0;
    proxy_request_buffering off;
    proxy_buffering off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
}

location ^~ /data/ {
    if ($csrf_check !~ ^ok-\S.+$) {
      return 403 "failed csrf check";
    }

    set $proxy_service "drs-server";
    proxy_pass http://drs-server$des_domain:8080;
    proxy_redirect http://$host/ https://$host/;

    client_max_body_size 0;
    proxy_request_buffering off;
    proxy_buffering off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;

}

location  /healthz {
    set $proxy_service "drs-server";
    proxy_pass http://drs-server$des_domain:8080;
}
