proxy_set_header Authorization "$access_token";
proxy_set_header X-Forwarded-For "$proxy_add_x_forwarded_for";
proxy_set_header X-UserId "$userid";
proxy_set_header X-ReqId "$request_id";
proxy_set_header X-SessionId "$session_id";
proxy_set_header X-VisitorId "$visitor_id";
proxy_set_header X-Original-URI $request_uri;
