{{- if .Values.serviceCreds.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceCreds.secretName }}
  labels:
    {{- include "syfon.labels" . | nindent 4 }}
type: Opaque
data:
  fence: {{ include "syfon.getOrGenSecret" (list .Values.serviceCreds.users.fence .Values.serviceCreds.secretName "fence" 20 .Release.Namespace) }}
  sheepdog: {{ include "syfon.getOrGenSecret" (list .Values.serviceCreds.users.sheepdog .Values.serviceCreds.secretName "sheepdog" 20 .Release.Namespace) }}
{{- end }}
